### ISSUE TITLE
buildkite/run: env-vars with key="value" does not work

### ISSUE THREAD

**Issue by v1v** [elastic/oblt-actions#248]
See https://github.com/elastic/elastic-agent/pull/7355

```yaml

      - uses: elastic/oblt-actions/buildkite/run@v1
        with:
          branch: ${{ github.ref_name }}
          pipeline: elastic-agent-helm-charts
          token: ${{ secrets.BUILDKITE_TOKEN }}
          wait-for: true
          env-vars: |
            SNAPSHOT=true
            HELM_REPO_ENV=dev
```

but, without quotes, it works:

```yaml

      - uses: elastic/oblt-actions/buildkite/run@v1
        with:
          branch: ${{ github.ref_name }}
          pipeline: elastic-agent-helm-charts
          token: ${{ secrets.BUILDKITE_TOKEN }}
          wait-for: true
          env-vars: |
            SNAPSHOT="true"
            HELM_REPO_ENV="dev"
```

### Tasks

- Support env vars with quote and unquote format in https://github.com/elastic/oblt-actions/tree/main/buildkite/run
- Add e2e tests in https://github.com/elastic/oblt-actions/blob/main/.github/workflows/test-buildkite-run.yml to test with env variables that contain quotes and no quotes (for instance, `SNAPSHOT=false` and `SNAPSHOT="true"`
- Only change what's needed and nothing else
